
FROM --platform=$BUILDPLATFORM rust:1.62-bullseye AS builder

WORKDIR /usr/src/assets
COPY . .
WORKDIR /usr/src/assets/migration

RUN apt-get update -y && apt-get install -y g++-aarch64-linux-gnu libc6-dev-arm64-cross apt-utils build-essential && rm -rf /var/lib/apt/lists/*
RUN cargo install --path .

FROM rust:1.62-alpine

COPY --from=builder /usr/src/assets/target/release/migration /usr/local/bin/migration
CMD ["migration"]
